from . import account_journal
from . import account_move
from . import account_tax
from . import product_template
from . import res_partner
from . import hacienda_config
from . import hacienda_document
from . import hacienda_catalog
from . import uom_uom
